export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_SURVEY_DASHBOARD_LIST = 'SET_SURVEY_DASHBOARD_LIST';
export const SET_CAMPAIGNS_LIST = 'SET_CAMPAIGNS_LIST';
export const SET_AUDIENCE_LIST = 'SET_AUDIENCE_LIST';
export const SET_USEREMAIL_PASSWORD = 'SET_USEREMAIL_PASSWORD';
export const SET_CAMPAIGN_BY_ID = 'SET_CAMPAIGN_BY_ID';
