export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_CAMPAIGNS_LIST = 'GET_CAMPAIGNS_LIST';
export const GET_AUDIENCE_LIST = 'GET_AUDIENCE_LIST';
export const GET_SURVEY_DASHBOARD_LIST = 'GET_SURVEY_DASHBOARD_LIST';
